# Generated by Django 5.2.4 on 2025-08-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuento',
            fields=[
                ('id_cuento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('version', models.CharField(max_length=45)),
                ('texto', models.TextField()),
                ('cantidad_palabras', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id_jardin', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('cuil', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id_palabra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('onda_voz', models.CharField(max_length=45)),
                ('resultado_esperado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='home.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pictograma',
            fields=[
                ('id_pictograma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('tamaño', models.CharField(max_length=45)),
                ('imagen', models.ImageField(upload_to='pictogramas/')),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuento')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.palabra')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='home.provincia'),
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jardin')),
                ('localida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion_Cuento',
            fields=[
                ('id_sesion_cuento', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_lectura', models.CharField(max_length=45)),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuento')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_General',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('sesion_cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sesion_cuento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('apellido', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=45)),
                ('edad', models.CharField(max_length=45)),
                ('jardìn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.jardin')),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
