# Generated by Django 5.2.4 on 2025-08-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuento',
            name='archivo_texto',
            field=models.FileField(default=1, upload_to='cuentos/textos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pictograma',
            name='cuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictogramas', to='home.cuento'),
        ),
        migrations.CreateModel(
            name='Narracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_audio', models.FileField(upload_to='narraciones/audio/')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completa', 'Completa'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
