# Generated by Django 5.2.4 on 2025-08-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cuento_archivo_texto_cuento_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuento',
            name='archivo_texto',
        ),
    ]
